# -*- coding: utf-8 -*-
"""datadata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ii71rvIfD7N6jBX-cZS76KP1f9cEKefV
"""

### 4급~6급 질병 top15 분석

import pandas as pd

# [1] 파일 경로 설정 및 인코딩 탐색
file_path = "/content/4_5_6_result.csv"
encodings = ['utf-8', 'cp949', 'euc-kr']

df = None
for enc in encodings:
    try:
        df = pd.read_csv(file_path, encoding=enc)
        print(f"인코딩 성공: {enc}")
        break
    except:
        continue

if df is None:
    print(f"❌ 오류: 파일 '{file_path}'을(를) 지정된 인코딩으로 읽을 수 없습니다.")
else:
    # [2] 열 이름 정제
    df.columns = df.columns.str.strip()

    # [3] 결측치 제거 및 숫자형 변환
    df = df.dropna(subset=["질병명", "계", "4급", "5급", "6급"])
    for col in ["계", "4급", "5급", "6급"]:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # [4] 등급별 전체 인원수 계산 및 비율
    total = df["계"].sum()
    grade_4 = df["4급"].sum()
    grade_5 = df["5급"].sum()
    grade_6 = df["6급"].sum()

    print("전체 판정 인원:", int(total))
    print("4급:", int(grade_4), f"({grade_4/total:.2%})")
    print("5급:", int(grade_5), f"({grade_5/total:.2%})")
    print("6급:", int(grade_6), f"({grade_6/total:.2%})")

    # 6급(면제자)
    top10_6급 = df.groupby("질병명")["6급"].sum().sort_values(ascending=False).head(15)
    print("\n6급 면제자 수 TOP 15 질병:")
    print(top10_6급)

    # 4급(보충역)
    top10_4급 = df.groupby("질병명")["4급"].sum().sort_values(ascending=False).head(15)
    print("\n 4급 보충역 판정 TOP 15 질병:")
    print(top10_4급)

    # 5급(전시근로역
    top10_5급 = df.groupby("질병명")["5급"].sum().sort_values(ascending=False).head(15)
    print("\n5급 전시근로역 판정 TOP 15 질병:")
    print(top10_5급)

### 19-29세 남자 비만율/스트레스 인지율/우울증상 유병률 분석
### 지역별 19년도-23년도 4급 보충역 수 분석

import pandas as pd

### 비만율
# [1] 데이터 불러오기
file_path = "obesity_prevalence.csv"
df = pd.read_csv(file_path, encoding='utf-8')

# [2] 컬럼명 공백 제거
df.columns = df.columns.str.strip()

# [3] 상단 설명 행 제거
df = df[df["성별(1)"] != "성별(1)"]

# [4] 19~29세 남성 필터링
df_young_men = df[
    (df["성별(1)"].str.strip() == "남자") &
    (df["특성별(2)"].str.strip() == "19-29세")
]

# [5] 2019~2023년 비만율(%)만 추출
columns_needed = ["특성별(2)", "2019.1", "2020.1", "2021.1", "2022.1", "2023.1"]
df_result = df_young_men[columns_needed].copy()

# [6] 컬럼명 정리
df_result.columns = ["연령대", "2019", "2020", "2021", "2022", "2023"]

# [7] 숫자형으로 변환
for year in ["2019", "2020", "2021", "2022", "2023"]:
    df_result[year] = df_result[year].astype(float)

# [8] 결과 출력
print("19~29세 남성 비만 유병률 (2019~2023)\n")
print(df_result)

### 스트레스
# [1] CSV 파일 경로 및 불러오기 (cp949 인코딩 사용)
file_path = "perceived_stress.csv"
df = pd.read_csv(file_path, encoding='cp949')

# [2] 컬럼명 공백 제거
df.columns = df.columns.str.strip()

# [3] 상단 설명 행 제거
df = df[df["성별(1)"] != "성별(1)"]

# [4] 19~29세 남성 데이터만 필터링
df_young_men = df[
    (df["성별(1)"].str.strip() == "남자") &
    (df["특성별(2)"].str.strip() == "19-29세")
]

# [5] 2019~2023년 스트레스 인지율 컬럼 추출
columns_needed = ["특성별(2)", "2019.1", "2020.1", "2021.1", "2022.1", "2023.1"]
df_result = df_young_men[columns_needed].copy()
df_result.columns = ["연령대", "2019", "2020", "2021", "2022", "2023"]

# [6] 데이터 숫자형으로 변환
for year in ["2019", "2020", "2021", "2022", "2023"]:
    df_result[year] = df_result[year].astype(float)

# [7] 평균 스트레스 인지율 계산 (단순 평균)
average_stress = df_result[["2019", "2020", "2021", "2022", "2023"]].mean(axis=1).iloc[0]

# [8] 결과 출력
print("\n19~29세 남성 스트레스 인지율 (2019~2023)")
print(df_result)
print(f"\n평균 스트레스 인지율: {average_stress:.2f}%")

### 우울 증상 유병률

# [1] 데이터 불러오기
file_path = '/content/depressive symptoms.csv'
df = pd.read_csv(file_path, encoding='utf-8')

# [2] 연령별 데이터만 필터링 (성별 구분 없음)
df_filtered = df[
    (df["특성별(1)"].str.strip() == "연령별") &
    (df["특성별(2)"].str.strip().isin(["만19세-24세", "만25세-29세"]))
]

# [3] 필요한 열만 선택하고 이름 정리
df_filtered = df_filtered[["특성별(2)", "2022", "2024"]].copy()
df_filtered.columns = ["연령대", "2022", "2024"]

# [4] 숫자형으로 변환
df_filtered["2022"] = df_filtered["2022"].astype(float)
df_filtered["2024"] = df_filtered["2024"].astype(float)

# [5] 평균 계산 (2022, 2024 평균 → 두 연령대 평균)
average_depression = df_filtered[["2022", "2024"]].mean().mean()

# [6] 결과 출력
print("\n19~29세 전체(남녀 포함) 우울 증상 유병률 (2022, 2024 기준)")
print(df_filtered)
print(f"\n평균 우울 증상 유병률: {average_depression:.2f}%")


### 4급 보충역 수 분석
# [1] CSV 파일 경로 및 불러오기
file_path = '/content/military_service_examination.csv'
df = pd.read_csv(file_path, encoding='cp949')

# [2] 컬럼명 공백 제거
df.columns = df.columns.str.strip()

# [3] '연도'는 2019~2023년, '지방청'은 전체, '판정구분'은 '보충역'인 행만 필터링
filtered = df[
    (df['연도'].between(2019, 2023))
]

# [4] 원하는 열만 선택
result = filtered[['연도', '지방청', '처분인원']]

# 선택사항: 연도별 전체 합계 보기
summary = result.groupby('연도')['처분인원'].sum().reset_index()
print("\n연도별 총 보충역 수")
print(summary)

import numpy as np
import matplotlib.pyplot as plt

plt.rcdefaults()


# PSQI 예측 (수면 시간이 적을수록 수면 질 저하)
def estimate_psqi(sleep_hours):
    return 6 + (7 - sleep_hours) * 1.5  # 수면 1시간 감소 시 PSQI 1.5 증가

# 우울 점수 예측 (논문 기반: β=0.67)
def estimate_depression_score(psqi):
    return 20 + 0.67 * (psqi - 6)

# 우울 점수 → 우울 유병률 (%)
def depression_score_to_prevalence(score):
    return min(0.01 * score, 0.5)  # 1점당 1% 유병률로 가정, 최대 50%

# 우울 유병률 → 4급 병역 판정 수 예측
def estimate_4th_grade_count(prevalence, total_population=50000):
    depressed_to_4th_ratio = 1218 / (0.20 * 50000)
    est_depressed = prevalence * total_population
    return int(est_depressed * depressed_to_4th_ratio)

# 수면 시나리오 시뮬레이션
sleep_hours_range = np.arange(5.0, 9.1, 0.5)
predicted_4th = []

for h in sleep_hours_range:
    psqi = estimate_psqi(h)
    depression_score = estimate_depression_score(psqi)
    depression_rate = depression_score_to_prevalence(depression_score)
    predicted = estimate_4th_grade_count(depression_rate)
    predicted_4th.append(predicted)

# 시각화
plt.figure(figsize=(10, 5))
plt.plot(sleep_hours_range, predicted_4th, marker='o', color='purple')
plt.title("Predicting the number of conscripts")
plt.xlabel("Sleep time (hours)")
plt.ylabel("Expected number of 4th graders)")
plt.grid(True)
plt.tight_layout()
plt.show()

### 청년 비만율이 감소하면 병역 4급 판정자 수가 얼마나 줄어들 수 있는지의 분석

import numpy as np
import matplotlib.pyplot as plt
plt.rcdefaults()

file_path = "/content/BMI_4.csv"
df = pd.read_csv(file_path, encoding='cp949')

# 컬럼 정리 및 필요한 열만 추출
df = df.rename(columns=lambda x: x.strip())
df = df[["연도", "처분인원수", "BMI사유4급처분인원수"]].copy()
df["연도"] = df["연도"].str[:4].astype(int)

# 최신년도 데이터 기준으로 분석
latest_year_data = df[df["연도"] == df["연도"].max()].iloc[0]
total_military_applicants = latest_year_data["처분인원수"]
obesity_4th_grade_count = latest_year_data["BMI사유4급처분인원수"]

# 현재 및 목표 비만율 설정
current_obesity_rate = 43.90  # 질병청 청년 비만율 (%)
target_obesity_rate = 35.0    # 목표 비만율 (%)

# [5] 목표 비만율 적용 시 예측 4급자 수
reduction_ratio = target_obesity_rate / current_obesity_rate
predicted_4th_grade_count = int(obesity_4th_grade_count * reduction_ratio)
reduction_count = obesity_4th_grade_count - predicted_4th_grade_count
reduction_percent = (reduction_count / obesity_4th_grade_count) * 100

# [6] 결과 출력
print("<result>")
print(f"- Current number of people with obesity level 4: {obesity_4th_grade_count:,}명")
print(f"- target obesity rate({target_obesity_rate}%) Number of predicted 4th graders when applied: {predicted_4th_grade_count:,}명")
print(f"- reduced number of people: {reduction_count:,}명")
print(f"- decline rate: {reduction_percent:.2f}%")

# [7] 시나리오별 시각화
obesity_rates = np.arange(current_obesity_rate, target_obesity_rate - 0.1, -1.0)
predicted_counts = [
    int(obesity_4th_grade_count * (rate / current_obesity_rate))
    for rate in obesity_rates
]

plt.figure(figsize=(10, 6))
plt.plot(obesity_rates, predicted_counts, marker='o', color='orange')
plt.title("Military service level 4 prediction", fontsize=14)
plt.xlabel("obesity rate (%)", fontsize=12)
plt.ylabel("BMI Military Service Number", fontsize=12)
plt.grid(True)
plt.gca().invert_xaxis()
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

plt.rcdefaults()

# 데이터 정의
data = {
    '연도': [2019, 2020, 2021, 2022, 2023],
    '비만율(%)': [37.3,  41.5,  40.0,  42.8,  43.9],
    '스트레스(%)': [28.7,  27.8,  24.1,  26.1,  24.5],
    "우울 증상 유병률(%)": [5.3, 5.7, 6.5, 5.9, 7.9],
    '4급자 수': [323763, 282167, 254361, 248361, 238604]
}
df = pd.DataFrame(data)

# 단일 회귀 (비만율 → 4급자 수)
X_single = df[['비만율(%)']]
y = df['4급자 수']
model_single = LinearRegression().fit(X_single, y)
r2_single = model_single.score(X_single, y)

# 다중 회귀 (비만율 + 스트레스 + 우울증상유병률)
X_multi = df[['비만율(%)', '스트레스(%)', '우울 증상 유병률(%)']]
model_multi = LinearRegression().fit(X_multi, y)
y_pred_multi = model_multi.predict(X_multi)
r2_multi = model_multi.score(X_multi, y)

# 회귀 평가 지표 mse, mae
mse = mean_squared_error(y, y_pred_multi)
rmse = np.sqrt(mse)  # RMSE 수동 계산
mae = mean_absolute_error(y, y_pred_multi)

# 변수 중요도 (회귀 계수)
coefficients = model_multi.coef_
feature_names = X_multi.columns
importance_df = pd.DataFrame({
    "변수": feature_names,
    "회귀계수": coefficients
}).sort_values(by="회귀계수", key=abs, ascending=False)

# 향후 변화에 따른 4급자 수 예측 (다중 회귀 기반)
future_obesity = np.arange(32, 38.5, 0.5)
future_input = pd.DataFrame({
    '비만율(%)': future_obesity,
    '스트레스(%)': 60,
    '우울 증상 유병률(%)': 5.5,
})


future_prediction = model_multi.predict(future_input)

# 시각화
plt.figure(figsize=(8, 5))
plt.scatter(X_single, y, color='blue', label='actual value')
plt.plot(future_obesity, model_single.predict(future_input[['비만율(%)']]), color='red', label='single regression line')
plt.plot(future_obesity, future_prediction, color='green', linestyle='--', label='Multiple regression prediction')
plt.xlabel("obesity rate (%)")
plt.ylabel("Expected 4th grader")
plt.title("Predicting the number of conscripts based on changes in obesity rates")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# 결과 요약 출력
print("\n✅ 회귀 성능 요약")
print(f"R² (단일 회귀): {r2_single:.3f}")
print(f"R² (다중 회귀): {r2_multi:.3f}")
print(f"RMSE: {rmse:.2f}")
print(f"MAE : {mae:.2f}")

print("\n✅ 변수 중요도 (회귀 계수)")
print(importance_df)

print("\n✅ 향후 비만율별 예측 4급자 수")
for rate, pred in zip(future_obesity, future_prediction):
    print(f"- 비만율 {rate:.1f}% → 예상 4급자 수: {int(pred):,}명")

"""
정신건강 지표(우울감 경험률, 우울증상 유병률)이
병역 판정 결과(4급 보충역 비율)에 미치는 영향을 분석

이 지표들이 10% 감소했을 때 병역 4급 판정 비율이 얼마나
줄어들 수 있는지 예측
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

plt.rcdefaults()

# [1] 데이터 불러오기
exp_path = "sigungu_depress_exp.csv"
rate_path = "sigungu_depress_rate.csv"

df_exp = pd.read_csv(exp_path, encoding='utf-8')
df_rate = pd.read_csv(rate_path, encoding='utf-8')

# [2] 평균 계산
df_exp = df_exp[['시군구별(1)', '2024', '2024.1', '2024.2', '2024.3', '2024.4']]
df_exp.iloc[:, 1:] = df_exp.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')
df_exp['우울감_평균'] = df_exp.iloc[:, 1:].mean(axis=1)

df_rate.columns = df_rate.columns.str.strip()
value_cols = ['2024', '2024.1', '2024.2', '2024.3', '2024.4']
df_rate[value_cols] = df_rate[value_cols].apply(pd.to_numeric, errors='coerce')
df_rate['우울증상_평균'] = df_rate[value_cols].mean(axis=1)

# [3] 병합
merged = pd.merge(
    df_exp[['시군구별(1)', '우울감_평균']],
    df_rate[['시군구별(1)', '우울증상_평균']],
    on='시군구별(1)', how='inner'
)

# [4] 병역 4급 비율 생성 (가상 데이터)
np.random.seed(42)
merged['병역_4급_비율'] = 5 + 0.03 * merged['우울감_평균'] + 0.04 * merged['우울증상_평균'] + np.random.normal(0, 1, len(merged))
merged = merged.dropna()

# [5] 회귀 분석을 위한 숫자형 변환
merged['우울감_평균'] = pd.to_numeric(merged['우울감_평균'], errors='coerce')
merged['우울증상_평균'] = pd.to_numeric(merged['우울증상_평균'], errors='coerce')
merged['병역_4급_비율'] = pd.to_numeric(merged['병역_4급_비율'], errors='coerce')
merged = merged.dropna(subset=['우울감_평균', '우울증상_평균', '병역_4급_비율'])

# [6] 회귀 분석
X = sm.add_constant(merged[['우울감_평균', '우울증상_평균']])
y = merged['병역_4급_비율']
model = sm.OLS(y, X).fit()

# [7] 10% 감소 시나리오 예측
# 두 지표(우울감, 우울증상)를 모두 * 0.9 (10% 감소)하여 다시 예측
scenario = merged.copy()
scenario['우울감_평균'] *= 0.9
scenario['우울증상_평균'] *= 0.9
X_new = sm.add_constant(scenario[['우울감_평균', '우울증상_평균']])
scenario['예측_4급_비율'] = model.predict(X_new)

# [8] 결과 정리
scenario['기존_4급_비율'] = merged['병역_4급_비율']
scenario['감소폭'] = scenario['기존_4급_비율'] - scenario['예측_4급_비율']
result = scenario[['시군구별(1)', '기존_4급_비율', '예측_4급_비율', '감소폭']].sort_values('감소폭', ascending=False)

# [9] 시군구 이름 영어로 변환
region_map = {
    "서울특별시": "Seoul", "부산광역시": "Busan", "대구광역시": "Daegu", "인천광역시": "Incheon",
    "광주광역시": "Gwangju", "대전광역시": "Daejeon", "울산광역시": "Ulsan", "세종특별자치시": "Sejong",
    "경기도": "Gyeonggi", "강원특별자치도": "Gangwon", "충청북도": "Chungbuk", "충청남도": "Chungnam",
    "전북특별자치도": "Jeonbuk", "전라남도": "Jeonnam", "경상북도": "Gyeongbuk", "경상남도": "Gyeongnam",
    "제주특별자치도": "Jeju"
}
result['Region'] = result['시군구별(1)'].map(region_map).fillna(result['시군구별(1)'])

# [10] 시각화
plt.figure(figsize=(14, 6))
plt.bar(result['Region'], result['감소폭'], color='green')
plt.title("Estimated Reduction in 4th Grade Military Rate\nwhen Depression Indicators Decrease by 10%", fontsize=13)
plt.xlabel("Region")
plt.ylabel("Reduction (%)")
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y')
plt.tight_layout()
plt.show()